BracesAroundHashParameters:
  Enabled: false

ClassLength:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    map: collect

Documentation:
  Enabled: false # don't require documentation

Encoding:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

LineLength:
  Max: 125

MethodLength:
  Max: 25

NumericLiterals:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

RedundantReturn:
  Enabled: false

SignalException:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false # we allow spaces inside hash brackets
