LineLength:
  Max: 125

CollectionMethods:
  PreferredMethods:
    map: collect

SignalException:
  Enabled: false

ClassLength:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

MethodLength:
  Max: 25

Encoding:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

RedundantReturn:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false # we allow spaces inside hash brackets

Documentation:
  Enabled: false # don't require documentation

NumericLiterals:
  Enabled: false
